mobilepulsa/urls.py
from django.urls import path

from .views import price_list

app_name = 'mobilepulsa'
urlpatterns = [
    path('', price_list, name='price_list'),
]

otomax_api/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mobilepulsa/', include('mobilepulsa.urls')),
    path('', views.home, name='home'),
]

mobilepulsa/models.py
from django.db import models
from django.contrib.auth.models import User


class PriceList(models.Model):
    status = models.CharField(max_length=50)
    icon_url = models.CharField(max_length=50)
    pulsa_code = models.CharField(max_length=50)
    pulsa_op = models.CharField(max_length=50)
    pulsa_nominal = models.CharField(max_length=50)
    pulsa_details = models.CharField(max_length=50)
    pulsa_price = models.CharField(max_length=50)
    pulsa_type = models.CharField(max_length=50)
    masaaktif = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.pulsa_code

traveloka/models.py
from django.db import models

# Create your models here.

mobilepulsa/views.py
from django.shortcuts import render
import json

from . import get_data


def price_list(request, * args, **kwargs):
    datas = get_data.price_list()

    context = {
        'datas': datas,
    }
    return render(request, 'mobilepulsa/price_list.html', context)

otomax_api/views.py
from django.shortcuts import render


def home(request, *args, **kwargs):
    return render(request, 'pages/home.html')

traveloka/views.py
from django.shortcuts import render

# Create your views here.

mobilepulsa/templates/mobilepulsa/price_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Price List{% endblock title %}

{% block content %}
<h5 class="my-4">Daftar Harga</h5>
<input class="form-control" id="myInput" type="text" placeholder="Search..">
<br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Kode</th>
      <th scope="col">Nominal</th>
      <th scope="col">Keterangan</th>
      <th scope="col">Harga</th>
      <th scope="col">Masa aktif</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody id="myTable">
    {% for data in datas %}
    <tr>
      <td><img src="{{ data.icon_url }}" alt=""></td>
      <td>{{ data.pulsa_code }}</td>
      <td>{{ data.pulsa_nominal }}</td>
      <td>{{ data.pulsa_details }}</td>
      <td>{{ data.pulsa_price|intcomma }}</td>
      <td>{{ data.masaaktif }}</td>
      <td>{{ data.status }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

{% block script %}
<script>
  $(document).ready(function () {
    $("#myInput").on("keyup", function () {
      var value = $(this).val().toLowerCase();
      $("#myTable tr").filter(function () {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

{% endblock script %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://bootswatch.com/4/cyborg/bootstrap.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'components/navbar.html' %}
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

    {% block script %}
    {% endblock script %}
</body>

</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
        aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'home' %}">OtomaX API</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Mobilepulsa</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'mobilepulsa:price_list' %}">Price List</a>
                    <!-- <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a> -->
                </div>
            </li>
            <li class="nav-item d-none">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0 d-none">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/pages/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{% endblock title %}

{% block content %}
<h4>Home Page</h4>
{% endblock content %}